# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# See https://github.com/actions/labeler/blob/main/README.md for docs.
'a: accessibility':
  - any-glob-to-any-file: '**/accessibility/*'
  - any-glob-to-any-file: '**/*accessibility*'
  - any-glob-to-any-file: '**/semantics/*'
  - any-glob-to-any-file: '**/*semantics*'

'a: animation':
  - any-glob-to-any-file: '**/animation/*'
  - any-glob-to-any-file: '**/*animation*'

'a: desktop':
  - any-glob-to-any-file: '**/linux/**/*'
  - any-glob-to-any-file: '**/macos/**/*'
  - any-glob-to-any-file: '**/windows/**/*'

'a: internationalization':
  - any-glob-to-any-file: 'packages/flutter_localizations/**/*'

'a: tests':
  - any-glob-to-any-file: 'packages/flutter_driver/**/*'
  - any-glob-to-any-file: 'packages/flutter_goldens/**/*'
  - any-glob-to-any-file: 'packages/flutter_goldens_client/**/*'
  - any-glob-to-any-file: 'packages/flutter_test/**/*'

'a: text input':
  - any-glob-to-any-file: '**/text/*'
  - any-glob-to-any-file: '**/*text*'

'd: api docs':
  - any-glob-to-any-file: 'examples/api/**/*'

'd: examples':
  - any-glob-to-any-file: 'examples/**/*'

engine:
  - any-glob-to-any-file: 'bin/internal/engine.version'

'f: cupertino':
  - any-glob-to-any-file: '**/cupertino/*'
  - any-glob-to-any-file: '**/*cupertino*'

'f: focus':
  - any-glob-to-any-file: '**/focus/*'
  - any-glob-to-any-file: '**/*focus*'

'f: gestures':
  - any-glob-to-any-file: '**/gestures/*'
  - any-glob-to-any-file: '**/*gestures*'

'f: material design':
  - any-glob-to-any-file: '**/material/*'
  - any-glob-to-any-file: '**/*material*'

'f: routes':
  - any-glob-to-any-file: '**/navigator/*'
  - any-glob-to-any-file: '**/*navigator*'
  - any-glob-to-any-file: '**/route/*'
  - any-glob-to-any-file: '**/*route*'

'f: scrolling':
  - any-glob-to-any-file: '**/*scroll*'
  - any-glob-to-any-file: '**/scroll/*'
  - any-glob-to-any-file: '**/*sliver*'
  - any-glob-to-any-file: '**/sliver/*'
  - any-glob-to-any-file: '**/*viewport*'
  - any-glob-to-any-file: '**/viewport/*'

framework:
  - any-glob-to-any-file: 'packages/flutter/**/*'
  - any-glob-to-any-file: 'packages/flutter_driver/**/*'
  - any-glob-to-any-file: 'packages/flutter_goldens/**/*'
  - any-glob-to-any-file: 'packages/flutter_goldens_client/**/*'
  - any-glob-to-any-file: 'packages/flutter_test/**/*'
  - any-glob-to-any-file: 'packages/integration_test/**/*'
  - any-glob-to-any-file: 'examples/api/**/*'

'f: integration_test':
  - any-glob-to-any-file: 'packages/integration_test/**/*'

platform-ios:
  - any-glob-to-any-file: 'packages/flutter_tools/lib/src/ios/**/*'

'customer: gallery':
  - any-glob-to-any-file: 'examples/flutter_gallery/**/*'

'c: tech-debt':
  - any-glob-to-any-file: '**/fix_data.yaml'
  - any-glob-to-any-file: '**/*.expect'
  - any-glob-to-any-file: '**/*test_fixes*'

tool:
  - any-glob-to-any-file: 'packages/flutter_tools/**/*'
  - any-glob-to-any-file: 'packages/fuchsia_remote_debug_protocol/**/*'
